_ARM64_REGISTERS_32BIT = {f'W{i}' for i in range(31)} | {'WZR'}
_ARM64_REGISTERS_64BIT= {f'X{i}' for i in range(31)} | {'XZR'}
_ARM64_STACK_REGISTER = {'SP'}
_ARM64_FRAME_POINTER = {'FP'}
_ARM64_LINK_REGISTER = {'LR'}

_ARM64_REGISTERS = _ARM64_REGISTERS_32BIT | _ARM64_REGISTERS_64BIT | _ARM64_STACK_REGISTER | \
                    _ARM64_LINK_REGISTER | _ARM64_FRAME_POINTER

_ARM64_OPCODES_ARITHMETIC = {"SUB", "ADD", "CMP"}
_ARM64_OPCODES_LOAD = {"LDR", "LDRSW", "LSL"}
_ARM64_OPCODES_STORE = {"STR"}
_ARM64_OPCODES_BRANCH = {"B", "BLT", "RET"}
_ARM64_OPCODES = _ARM64_OPCODES_ARITHMETIC | _ARM64_OPCODES_LOAD | _ARM64_OPCODES_STORE | \
                    _ARM64_OPCODES_BRANCH